language: node_js
env: CXX=g++-4.8
node_js:
    - "6"
sudo: false
compiler:
  - clang
  - gcc
install:
    - npm install -g mocha
    - npm install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - npm test
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - xvfb
            - gcc-4.8
            - g++-4.8

